#!/bin/bash
__get_first_word()
{
    while read -r first rest; do
        echo "$first"
    done
}

_project()
{
    COMP_WORDBREAKS=${COMP_WORDBREAKS//:}
    local cur prev words cword split
    local debug=0
    _init_completion -s -n : || return

    case $prev in
        projec*) # replace with partial name
            COMMANDS=$(project --raw list | __get_first_word )
            COMPREPLY=(`compgen -W "$COMMANDS" -- "$cur"`)
            return 0
            ;;
    esac

    case $cur in
        -*)
            COMMANDS=$( project ${words[1]} --help | sed 's/[][]//g' | _parse_help - )
            COMPREPLY=(`compgen -W "$COMMANDS" -- "$cur"`)
            return
            ;;
        *)
            _filedir
            return
            ;;
    esac
} &&
complete -F _project -o nospace application
